name: gs1_barcode_parser
description: The barcode parser is a library for handling the contents of GS1 barcodes.
version: 0.0.6
homepage: https://github.com/mobui/gs1_barcode_parser

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: ^1.15.4


